#!/usr/bin/env bash
# Write a development-only .env if one does not already exist.
# These are non-secret local dev values only. Production secrets are supplied
# separately (see .env.example and docs/deployment.md).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if [ -f .env ]; then
  exit 0
fi

cat > .env <<'EOF'
# Auto-generated by .cursor/write-dev-env.sh for the Cloud Agent dev environment.
# Development-only, non-secret values. Do NOT use in production.
DATABASE_URL="postgresql://tinda:tinda@localhost:5432/tinda?schema=public"
SESSION_SECRET="dev-session-secret-at-least-32-characters-long-abc"
APP_URL="http://localhost:3000"
STORAGE_DRIVER="local"
SEED_PASSWORD="ChangeMe123!"
EOF

echo "Wrote development .env"
